import { Wishlist, WishlistAccent, WishlistVisibility } from "@/types/wishlist";

export const stats = [
  { label: "Wishlists", value: 5 },
  { label: "Total Items", value: 46 },
  { label: "Reserved", value: 3 },
  { label: "Purchased", value: 2 },
];

export const wishlists: Wishlist[] = [
  {
    id: "1",
    user_id: "user-1",
    title: "Birthday Wishes",
    description: null,
    image_url: null,
    created_at: null,
    visibility_type: WishlistVisibility.FriendsOnly,
    accent_type: WishlistAccent.Pink,
    event_date: null,
    items_count: 8,
    can_edit: true,
    is_owner: true,
    access_type: null,
    owner_nickname: null,
  },
  {
    id: "2",
    user_id: "user-1",
    title: "Home Office Setup",
    description: null,
    image_url: null,
    created_at: null,
    visibility_type: WishlistVisibility.Public,
    accent_type: WishlistAccent.Blue,
    event_date: null,
    items_count: 5,
    can_edit: true,
    is_owner: true,
    access_type: null,
    owner_nickname: null,
  },
  {
    id: "3",
    user_id: "user-1",
    title: "Kitchen Essentials",
    description: null,
    image_url: null,
    created_at: null,
    visibility_type: WishlistVisibility.FriendsOnly,
    accent_type: WishlistAccent.Peach,
    event_date: null,
    items_count: 12,
    can_edit: true,
    is_owner: true,
    access_type: null,
    owner_nickname: null,
  },
  {
    id: "4",
    user_id: "user-1",
    title: "Travel Gear",
    description: null,
    image_url: null,
    created_at: null,
    visibility_type: WishlistVisibility.Private,
    accent_type: WishlistAccent.Mint,
    event_date: null,
    items_count: 6,
    can_edit: true,
    is_owner: true,
    access_type: null,
    owner_nickname: null,
  },
  {
    id: "5",
    user_id: "user-1",
    title: "Books to Read",
    description: null,
    image_url: null,
    created_at: null,
    visibility_type: WishlistVisibility.Public,
    accent_type: WishlistAccent.Lavender,
    event_date: null,
    items_count: 15,
    can_edit: true,
    is_owner: true,
    access_type: null,
    owner_nickname: null,
  },
];
