import { Wishlist, WishlistVisibility, WishlistAccent } from "@/types/wishlist";

export const stats = [
  { label: "Wishlists", value: 5 },
  { label: "Total Items", value: 46 },
  { label: "Reserved", value: 3 },
  { label: "Purchased", value: 2 },
];

export const wishlists: Wishlist[] = [
  {
    id: "1",
    user_id: "",
    title: "Birthday Wishes",
    description: null,
    itemsCount: 8,
    visibility_type: WishlistVisibility.FriendsOnly,
    accent_type: WishlistAccent.Pink,
    image_url: null,
    created_at: "",
  },
  {
    id: "2",
    user_id: "",
    title: "Home Office Setup",
    description: null,
    itemsCount: 5,
    visibility_type: WishlistVisibility.Public,
    accent_type: WishlistAccent.Blue,
    image_url: null,
    created_at: "",
  },
  {
    id: "3",
    user_id: "",
    title: "Kitchen Essentials",
    description: null,
    itemsCount: 12,
    visibility_type: WishlistVisibility.FriendsOnly,
    accent_type: WishlistAccent.Peach,
    image_url: null,
    created_at: "",
  },
  {
    id: "4",
    user_id: "",
    title: "Travel Gear",
    description: null,
    itemsCount: 6,
    visibility_type: WishlistVisibility.Private,
    accent_type: WishlistAccent.Mint,
    image_url: null,
    created_at: "",
  },
  {
    id: "5",
    user_id: "",
    title: "Books to Read",
    description: null,
    itemsCount: 15,
    visibility_type: WishlistVisibility.Public,
    accent_type: WishlistAccent.Lavender,
    image_url: null,
    created_at: "",
  },
];
