name: Native Build

defaults:
  tools:
    node: 22.14.0
    corepack: true
    pnpm: 11.9.0

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        required: true
        description: EAS build profile to use.
        default: development
        options:
          - development
          - staging
          - production

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: ${{ inputs.profile || 'development' }}
      message: Build from ${{ github.ref_name }}

  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: ${{ inputs.profile || 'development' }}
      message: Build from ${{ github.ref_name }}
