name: Native Build

defaults:
  tools:
    node: 22.11.0
    corepack: true
    pnpm: 11.9.0

on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        required: true
        description: EAS build profile to use.
        default: preview
        options:
          - development
          - preview
          - production
      environment:
        type: environment
        required: true
        description: EAS environment variables to use.
        default: preview

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}-${{ inputs.profile || 'preview' }}

jobs:
  build_android:
    name: Build Android
    type: build
    environment: ${{ inputs.environment || 'preview' }}
    params:
      platform: android
      profile: ${{ inputs.profile || 'preview' }}
      message: Build from ${{ github.ref_name }}

  build_ios:
    name: Build iOS
    type: build
    environment: ${{ inputs.environment || 'preview' }}
    params:
      platform: ios
      profile: ${{ inputs.profile || 'preview' }}
      message: Build from ${{ github.ref_name }}
