name: Native Development Build

defaults:
  tools:
    node: 22.14.0
    corepack: true
    pnpm: 11.9.0

on:
  push:
    branches:
      - dev
    paths:
      - apps/native/**
      - "!**/*.md"

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  build_android:
    name: Build Android Development
    type: build
    environment: development
    params:
      platform: android
      profile: development
      message: Development build from ${{ github.ref_name }}

  build_ios:
    name: Build iOS Development
    type: build
    environment: development
    params:
      platform: ios
      profile: development
      message: Development build from ${{ github.ref_name }}

  publish_update:
    name: Publish Development Update
    needs: [build_android, build_ios]
    type: update
    environment: development
    params:
      platform: all
      channel: development
      message: Development update from ${{ github.ref_name }}
