name: Native Production Build

defaults:
  tools:
    node: 22.14.0
    corepack: true
    pnpm: 11.9.0

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - apps/native/**
#       - "!**/*.md"

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  build_android:
    name: Build Android Production
    type: build
    environment: production
    params:
      platform: android
      profile: production
      message: Production build from ${{ github.ref_name }}

  build_ios:
    name: Build iOS Production
    type: build
    environment: production
    params:
      platform: ios
      profile: production
      message: Production build from ${{ github.ref_name }}
