name: Native Staging Deploy

defaults:
  tools:
    node: 22.14.0
    corepack: true
    pnpm: 11.9.0

# on:
#   push:
#     branches:
#       - staging
#     paths:
#       - apps/native/**
#       - "!**/*.md"

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  build_ios:
    name: Build iOS Staging
    type: build
    environment: preview
    params:
      platform: ios
      profile: staging
      message: Staging build from ${{ github.ref_name }}

  submit_ios:
    name: Submit to TestFlight
    needs: [build_ios]
    type: submit
    environment: preview
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: staging

  build_android:
    name: Build Android Staging
    type: build
    environment: preview
    params:
      platform: android
      profile: staging
      message: Staging build from ${{ github.ref_name }}

  submit_android:
    name: Submit to Google Play Internal Testing
    needs: [build_android]
    type: submit
    environment: preview
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: staging
