/**
 * Regenerates components/ui/flag-data.ts — the inline circular-flag SVG map used by
 * <Flag>. Run after adding a locale or currency so a flag exists for it:
 *   node gen-flags.mjs
 *
 * Source of truth for which flags are needed:
 *   - locales   → country codes in lib/locale-flags.ts (LOCALE_TO_COUNTRY values)
 *   - currencies→ first two letters of each SUPPORTED_CURRENCIES code
 * Flags come from HatScripts/circle-flags (MIT) via jsDelivr.
 */
import fs from "fs";
import https from "https";

// Country codes referenced by the locale map.
const localeFlags = fs.readFileSync("lib/locale-flags.ts", "utf8");
const localeSection = localeFlags.slice(
  localeFlags.indexOf("LOCALE_TO_COUNTRY"),
  localeFlags.indexOf("countryForLocale"),
);
const countries = new Set([...localeSection.matchAll(/:\s*"([a-z]{2})"/g)].map((m) => m[1]));

// Country codes referenced by currencies (ISO 4217 first two letters).
const currencies = fs.readFileSync("../../packages/backend/lib/currencies.ts", "utf8");
for (const m of currencies.matchAll(/code:\s*"([A-Z]{2})[A-Z]"/g)) {
  countries.add(m[1].toLowerCase());
}

// circle-flags stores the EU flag under a different filename.
const FILENAME_OVERRIDES = { eu: "european_union" };

function download(cc) {
  const file = FILENAME_OVERRIDES[cc] ?? cc;
  return new Promise((resolve, reject) => {
    https
      .get(`https://cdn.jsdelivr.net/gh/HatScripts/circle-flags/flags/${file}.svg`, (res) => {
        if (res.statusCode !== 200) {
          res.resume();
          reject(new Error(`${cc}: HTTP ${res.statusCode}`));
          return;
        }
        let data = "";
        res.on("data", (c) => (data += c));
        res.on("end", () => resolve(data.trim()));
      })
      .on("error", reject);
  });
}

// circle-flags reuse short ids (a, b, ...) across files; react-native-svg resolves
// `url(#id)` in a shared scope, so namespace every id per country.
function namespaceIds(svg, cc) {
  const prefix = `f${cc}_`;
  for (const id of new Set([...svg.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1]))) {
    const esc = id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    svg = svg
      .replace(new RegExp(`\\bid="${esc}"`, "g"), `id="${prefix}${id}"`)
      .replace(new RegExp(`url\\(#${esc}\\)`, "g"), `url(#${prefix}${id})`)
      .replace(new RegExp(`(xlink:href|href)="#${esc}"`, "g"), `$1="#${prefix}${id}"`);
  }
  return svg;
}

const list = [...countries].sort();
console.log(`Downloading ${list.length} flags...`);
const entries = [];
for (const cc of list) {
  const svg = namespaceIds(await download(cc), cc);
  entries.push(`  ${cc}: ${JSON.stringify(svg)},`);
}

const out = `// AUTO-GENERATED by gen-flags.mjs — do not edit by hand.
// Circular country flags from HatScripts/circle-flags (MIT). Internal SVG ids are
// namespaced per country so react-native-svg can render many flags together safely.

export const FLAG_SVGS: Record<string, string> = {
${entries.join("\n")}
};
`;
fs.writeFileSync("components/ui/flag-data.ts", out);
console.log(`Wrote components/ui/flag-data.ts with ${entries.length} flags`);
