// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'pink-light', 'pink-dark', 'blue-light', 'blue-dark', 'peach-light', 'peach-dark', 'mint-light', 'mint-dark', 'lavender-light', 'lavender-dark']
    }
}

export {}
