// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'pink', 'pink-dark', 'blue', 'blue-dark', 'peach', 'peach-dark', 'mint', 'mint-dark', 'lavender', 'lavender-dark']
    }
}

export {}
