import { CreateMenuHost } from "@/components/create/create-menu";
import { getThemeMode, useNavigationTheme } from "@/lib/theme";
import { useAuth } from "@/providers/auth-provider";
import { useUserGuide } from "@/components/user-guide/user-guide-provider";
import { useUnreadNotificationsCount } from "@/hooks/use-notifications";
import { Redirect, usePathname } from "expo-router";
import { NativeTabs } from "expo-router/unstable-native-tabs";
import { useGT } from "gt-react-native";
import * as React from "react";
import { useUniwind } from "uniwind";

export const unstable_settings = {
  initialRouteName: "wishlists",
};

export default function TabsLayout() {
  const t = useGT();
  const { session } = useAuth();
  const pathname = usePathname();
  const { handleTabPress } = useUserGuide();
  const { data: unreadCount = 0 } = useUnreadNotificationsCount();
  const { theme } = useUniwind();
  const themeMode = getThemeMode(theme);
  const navigationTheme = useNavigationTheme(theme);
  const [createOpen, setCreateOpen] = React.useState(false);
  const primaryColor =
    typeof navigationTheme.colors.primary === "string" ? navigationTheme.colors.primary : "#208aef";
  const selectedTabBackground = themeMode === "dark" ? `${primaryColor}24` : `${primaryColor}18`;
  const unreadBadge = unreadCount > 99 ? "99+" : String(unreadCount);

  if (!session) {
    return <Redirect href={"/(auth)/sign-in" as never} />;
  }

  if (pathname === "/") {
    return <Redirect href={"/(tabs)/wishlists" as never} />;
  }

  return (
    <CreateMenuHost open={createOpen} onOpenChange={setCreateOpen}>
      <NativeTabs
        backgroundColor={navigationTheme.colors.card}
        badgeBackgroundColor={navigationTheme.colors.notification}
        badgeTextColor="#ffffff"
        blurEffect={themeMode === "dark" ? "systemMaterialDark" : "systemMaterialLight"}
        disableTransparentOnScrollEdge
        indicatorColor={selectedTabBackground}
        labelVisibilityMode="labeled"
        tintColor={navigationTheme.colors.primary}
      >
        <NativeTabs.Trigger
          name="wishlists"
          listeners={{
            tabPress: () => handleTabPress("wishlists"),
          }}
        >
          <NativeTabs.Trigger.Icon sf="gift.fill" md="featured_seasonal_and_gifts" />
          <NativeTabs.Trigger.Label>{t("Wishlists")}</NativeTabs.Trigger.Label>
          {unreadCount > 0 ? (
            <NativeTabs.Trigger.Badge>{unreadBadge}</NativeTabs.Trigger.Badge>
          ) : null}
        </NativeTabs.Trigger>
        <NativeTabs.Trigger
          name="secret-santa"
          listeners={{
            tabPress: () => handleTabPress("secret-santa"),
          }}
        >
          {/* No SF Symbol or Material symbol exists for Santa, so both
              platforms use a monochrome Santa-hat template image tinted like
              the other tab symbols. Asset generated by
              scripts/gen-secret-santa-icon.mjs. */}
          <NativeTabs.Trigger.Icon
            src={require("@/assets/images/secret-santa-tab.png")}
            renderingMode="template"
          />
          <NativeTabs.Trigger.Label>{t("Secret Santa")}</NativeTabs.Trigger.Label>
        </NativeTabs.Trigger>
        {/* Disabled trigger: the native side blocks selection but still emits
            tabPress, which opens the create menu instead of navigating. The
            search role uses the separate native action slot on supported iOS. */}
        <NativeTabs.Trigger
          name="create"
          disabled
          role="search"
          listeners={{
            tabPress: () => setCreateOpen(true),
          }}
        >
          {/* Template PNG instead of the plus.circle.fill SF symbol: the tab
              bar renders template images at their intrinsic point size (30pt
              vs ~25pt for symbols), making the + more prominent on iOS. Asset
              generated by scripts/gen-tab-plus-icon.mjs. */}
          <NativeTabs.Trigger.Icon
            md="add_circle"
            src={require("@/assets/images/tab-plus.png")}
            renderingMode="template"
          />
          <NativeTabs.Trigger.Label>{t("Create")}</NativeTabs.Trigger.Label>
        </NativeTabs.Trigger>
        <NativeTabs.Trigger
          name="friends"
          listeners={{
            tabPress: () => handleTabPress("friends"),
          }}
        >
          <NativeTabs.Trigger.Icon sf="person.2.fill" md="group" />
          <NativeTabs.Trigger.Label>{t("Friends")}</NativeTabs.Trigger.Label>
        </NativeTabs.Trigger>
        <NativeTabs.Trigger
          name="profile"
          listeners={{
            tabPress: () => handleTabPress("profile"),
          }}
        >
          <NativeTabs.Trigger.Icon sf="person.crop.circle" md="account_circle" />
          <NativeTabs.Trigger.Label>{t("Profile")}</NativeTabs.Trigger.Label>
        </NativeTabs.Trigger>
      </NativeTabs>
    </CreateMenuHost>
  );
}
