import { getThemeMode, useNavigationTheme } from "@/lib/theme";
import { useUserGuide } from "@/components/user-guide/user-guide-provider";
import { useUnreadNotificationsCount } from "@/hooks/use-notifications";
import { NativeTabs } from "expo-router/unstable-native-tabs";
import { useGT } from "gt-react-native";
import { useUniwind } from "uniwind";

type IosTabBarProps = {
  onCreatePress: () => void;
};

export function IosTabBar({ onCreatePress }: IosTabBarProps) {
  const t = useGT();
  const { handleTabPress } = useUserGuide();
  const { data: unreadCount = 0 } = useUnreadNotificationsCount();
  const { theme } = useUniwind();
  const themeMode = getThemeMode(theme);
  const navigationTheme = useNavigationTheme(theme);
  const primaryColor =
    typeof navigationTheme.colors.primary === "string" ? navigationTheme.colors.primary : "#208aef";
  const selectedTabBackground = themeMode === "dark" ? `${primaryColor}24` : `${primaryColor}18`;
  const unreadBadge = unreadCount > 99 ? "99+" : String(unreadCount);

  return (
    <NativeTabs
      backgroundColor={navigationTheme.colors.card}
      badgeBackgroundColor={navigationTheme.colors.notification}
      badgeTextColor="#ffffff"
      blurEffect={themeMode === "dark" ? "systemMaterialDark" : "systemMaterialLight"}
      disableTransparentOnScrollEdge
      indicatorColor={selectedTabBackground}
      labelVisibilityMode="labeled"
      tintColor={navigationTheme.colors.primary}
    >
      <NativeTabs.Trigger
        name="wishlists"
        listeners={{
          tabPress: () => handleTabPress("wishlists"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="gift.fill" md="featured_seasonal_and_gifts" />
        <NativeTabs.Trigger.Label>{t("Wishlists")}</NativeTabs.Trigger.Label>
        {unreadCount > 0 ? <NativeTabs.Trigger.Badge>{unreadBadge}</NativeTabs.Trigger.Badge> : null}
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="secret-santa"
        listeners={{
          tabPress: () => handleTabPress("secret-santa"),
        }}
      >
        {/* No SF Symbol or Material symbol exists for Santa, so both
            platforms use a monochrome Santa-hat template image tinted like
            the other tab symbols. Asset generated by
            scripts/gen-secret-santa-icon.mjs. */}
        <NativeTabs.Trigger.Icon
          src={require("@/assets/images/secret-santa-tab.png")}
          renderingMode="template"
        />
        <NativeTabs.Trigger.Label>{t("Secret Santa")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      {/* Disabled trigger: the native side blocks selection but still emits
          tabPress, which opens the create menu instead of navigating. The
          search role uses the separate native action slot on supported iOS. */}
      <NativeTabs.Trigger
        name="create"
        disabled
        role="search"
        listeners={{
          tabPress: onCreatePress,
        }}
      >
        {/* Template PNG instead of the plus.circle.fill SF symbol: the tab
            bar renders template images at their intrinsic point size (30pt
            vs ~25pt for symbols), making the + more prominent on iOS. Asset
            generated by scripts/gen-tab-plus-icon.mjs. */}
        <NativeTabs.Trigger.Icon
          md="add_circle"
          src={require("@/assets/images/tab-plus.png")}
          renderingMode="template"
        />
        <NativeTabs.Trigger.Label>{t("Create")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="friends"
        listeners={{
          tabPress: () => handleTabPress("friends"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="person.2.fill" md="group" />
        <NativeTabs.Trigger.Label>{t("Friends")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="profile"
        listeners={{
          tabPress: () => handleTabPress("profile"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="person.crop.circle" md="account_circle" />
        <NativeTabs.Trigger.Label>{t("Profile")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
