import {
  type NativeAccentName,
  getThemeAccent,
  getThemeMode,
  useNavigationTheme,
} from "@/lib/theme";
import { useUserGuide } from "@/components/user-guide/user-guide-provider";
import { useUnreadNotificationsCount } from "@/hooks/use-notifications";
import { NativeTabs } from "expo-router/unstable-native-tabs";
import { useGT } from "gt-react-native";
import { useCSSVariable, useUniwind } from "uniwind";

/**
 * Pre-colored Create icons, one per accent. iOS 26 ignores tint on unselected
 * tab items and draws template images black in light mode, so the Create icon
 * is rendered as-is instead. Assets generated by scripts/gen-tab-plus-icon.mjs.
 */
const CREATE_ICONS: Record<NativeAccentName, number> = {
  pink: require("@/assets/images/tab-plus-pink.png"),
  blue: require("@/assets/images/tab-plus-blue.png"),
  peach: require("@/assets/images/tab-plus-peach.png"),
  mint: require("@/assets/images/tab-plus-mint.png"),
  lavender: require("@/assets/images/tab-plus-lavender.png"),
};

type IosTabBarProps = {
  onCreatePress: () => void;
};

export function IosTabBar({ onCreatePress }: IosTabBarProps) {
  const t = useGT();
  const { handleTabPress } = useUserGuide();
  const { data: unreadCount = 0 } = useUnreadNotificationsCount();
  const { theme } = useUniwind();
  const themeMode = getThemeMode(theme);
  const navigationTheme = useNavigationTheme(theme);
  const primaryColor =
    typeof navigationTheme.colors.primary === "string" ? navigationTheme.colors.primary : "#208aef";
  const selectedTabBackground = themeMode === "dark" ? `${primaryColor}24` : `${primaryColor}18`;
  // Unselected tabs otherwise fall back to the system label color (pure black
  // in light mode); use the muted text token to match the Android tab bar.
  // iOS 26+ ignores this for unselected items and uses its own glass styling.
  const mutedTextColor = useCSSVariable("--color-text-muted");
  const inactiveColor = typeof mutedTextColor === "string" ? mutedTextColor : "#6b7280";
  const unreadBadge = unreadCount > 99 ? "99+" : String(unreadCount);

  return (
    <NativeTabs
      backgroundColor={navigationTheme.colors.card}
      badgeBackgroundColor={navigationTheme.colors.notification}
      badgeTextColor="#ffffff"
      blurEffect={themeMode === "dark" ? "systemMaterialDark" : "systemMaterialLight"}
      disableTransparentOnScrollEdge
      iconColor={{ default: inactiveColor, selected: primaryColor }}
      indicatorColor={selectedTabBackground}
      labelStyle={{
        default: { fontSize: 10, color: inactiveColor },
        selected: { fontSize: 10, color: primaryColor },
      }}
      labelVisibilityMode="labeled"
      tintColor={navigationTheme.colors.primary}
    >
      <NativeTabs.Trigger
        name="wishlists"
        disableAutomaticContentInsets
        listeners={{
          tabPress: () => handleTabPress("wishlists"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="gift.fill" md="featured_seasonal_and_gifts" />
        <NativeTabs.Trigger.Label>{t("Wishlists")}</NativeTabs.Trigger.Label>
        {unreadCount > 0 ? (
          <NativeTabs.Trigger.Badge>{unreadBadge}</NativeTabs.Trigger.Badge>
        ) : null}
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="secret-santa"
        disableAutomaticContentInsets
        listeners={{
          tabPress: () => handleTabPress("secret-santa"),
        }}
      >
        {/* No SF Symbol or Material symbol exists for Santa, so both
            platforms use a monochrome Santa-hat template image tinted like
            the other tab symbols. Asset generated by
            scripts/gen-secret-santa-icon.mjs. */}
        <NativeTabs.Trigger.Icon
          src={require("@/assets/images/secret-santa-tab.png")}
          renderingMode="template"
        />
        <NativeTabs.Trigger.Label>{t("Secret Santa")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      {/* Disabled trigger: the native side blocks selection but still emits
          tabPress, which opens the create menu instead of navigating. The
          search role uses the separate native action slot on supported iOS. */}
      <NativeTabs.Trigger
        name="create"
        disabled
        role="search"
        listeners={{
          tabPress: onCreatePress,
        }}
      >
        {/* PNG instead of the plus.circle.fill SF symbol: the tab bar renders
            images at their intrinsic point size (30pt vs ~25pt for symbols),
            making the + more prominent on iOS. */}
        <NativeTabs.Trigger.Icon
          md="add_circle"
          src={CREATE_ICONS[getThemeAccent(theme)]}
          renderingMode="original"
        />
        <NativeTabs.Trigger.Label>{t("Create")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="friends"
        disableAutomaticContentInsets
        listeners={{
          tabPress: () => handleTabPress("friends"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="person.2.fill" md="group" />
        <NativeTabs.Trigger.Label>{t("Friends")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
      <NativeTabs.Trigger
        name="profile"
        disableAutomaticContentInsets
        listeners={{
          tabPress: () => handleTabPress("profile"),
        }}
      >
        <NativeTabs.Trigger.Icon sf="person.crop.circle" md="account_circle" />
        <NativeTabs.Trigger.Label>{t("Profile")}</NativeTabs.Trigger.Label>
      </NativeTabs.Trigger>
    </NativeTabs>
  );
}
