type TranslationsModule = { default: Record<string, unknown> };

// Runtime catalogs are generated by scripts/build-gt-catalogs.mjs from src/i18n/labels.*.json.
const loaders: Record<string, () => Promise<TranslationsModule>> = {
  uk: () => import("../public/_gt/uk.json"),
  de: () => import("../public/_gt/de.json"),
  es: () => import("../public/_gt/es.json"),
  fr: () => import("../public/_gt/fr.json"),
  ja: () => import("../public/_gt/ja.json"),
  it: () => import("../public/_gt/it.json"),
  pt: () => import("../public/_gt/pt.json"),
  zh: () => import("../public/_gt/zh.json"),
  pl: () => import("../public/_gt/pl.json"),
  ko: () => import("../public/_gt/ko.json"),
  nl: () => import("../public/_gt/nl.json"),
  hi: () => import("../public/_gt/hi.json"),
  tr: () => import("../public/_gt/tr.json"),
  vi: () => import("../public/_gt/vi.json"),
  th: () => import("../public/_gt/th.json"),
  id: () => import("../public/_gt/id.json"),
  cs: () => import("../public/_gt/cs.json"),
  sk: () => import("../public/_gt/sk.json"),
  hu: () => import("../public/_gt/hu.json"),
  ro: () => import("../public/_gt/ro.json"),
  bg: () => import("../public/_gt/bg.json"),
  el: () => import("../public/_gt/el.json"),
  sv: () => import("../public/_gt/sv.json"),
  da: () => import("../public/_gt/da.json"),
  nb: () => import("../public/_gt/nb.json"),
  fi: () => import("../public/_gt/fi.json"),
  hr: () => import("../public/_gt/hr.json"),
  sr: () => import("../public/_gt/sr.json"),
  sl: () => import("../public/_gt/sl.json"),
  lt: () => import("../public/_gt/lt.json"),
  lv: () => import("../public/_gt/lv.json"),
  et: () => import("../public/_gt/et.json"),
  bn: () => import("../public/_gt/bn.json"),
  ms: () => import("../public/_gt/ms.json"),
  fil: () => import("../public/_gt/fil.json"),
  "zh-Hant": () => import("../public/_gt/zh-Hant.json"),
  ar: () => import("../public/_gt/ar.json"),
  he: () => import("../public/_gt/he.json"),
  fa: () => import("../public/_gt/fa.json"),
  ur: () => import("../public/_gt/ur.json"),
};

export default async function loadTranslations(locale: string) {
  const load = loaders[locale];
  if (!load) {
    return {};
  }
  try {
    const mod = await load();
    return mod.default;
  } catch {
    return {};
  }
}
